// "use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavLinks from './ui/NavBar';
// import { Transition } from 'react-transition-group';
import Footer from "./ui/Footer";
import "./ui/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div  className="fixed w-full z-50">
          <NavLinks/>
        </div>
        {/* <Transition in={true} timeout={300} classnames="page"> */}
        {/* fadeIn */}
        <div className="pt-16 ">
            {children}
          </div>
        {/* </Transition> */}
        <Footer />
      </body>
    </html>
  );
}
